import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export const store = new Vuex.Store({
  state: {
    plans: [
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 0,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 0,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 2,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 2,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
      {
        name: "xxxxxxx",
        principal: "张三",
        date: 1581672605401,
        period: 5,
        remainingTimes: 5,
        state: 1,
      },
    ],
  },
});
